// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqwkVBszytwGKM2bj8UuQgpZ1b2x4NrU',
    appId: '1:677629900977:web:39fb535401e9b9da3f4a90',
    messagingSenderId: '677629900977',
    projectId: 'logcekrekqu',
    authDomain: 'logcekrekqu.firebaseapp.com',
    storageBucket: 'logcekrekqu.firebasestorage.app',
    measurementId: 'G-KDQ0BLPDDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj9FawSnsvaqS5IjOBBxMYoqLfZHNktiI',
    appId: '1:677629900977:android:ef7608917d75bfb33f4a90',
    messagingSenderId: '677629900977',
    projectId: 'logcekrekqu',
    storageBucket: 'logcekrekqu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1eWN-D8BmFY8uWzKysxpSzzUVz_ql_To',
    appId: '1:677629900977:ios:b40a6c4514e2d5c53f4a90',
    messagingSenderId: '677629900977',
    projectId: 'logcekrekqu',
    storageBucket: 'logcekrekqu.firebasestorage.app',
    androidClientId: '677629900977-toav4hp4itlbu44l1dm00u4nclbisosj.apps.googleusercontent.com',
    iosClientId: '677629900977-0cp0sh5phuk6l155lsn8dtil5nt6s3jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cekrequFrontend',
  );
}
